#!/bin/bash
set -e

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` == 'scripts' ]]; then
  cd ../
else
  cd `dirname ${CWD}`
fi

if [[ ! -f $1 ]]; then
  echo File is not exists ...
  exit 1;
fi

PDF_FILENAME=${1%.tex}.pdf
SVG_FILENAME=${1%.tex}.svg

# Generate PDF file, see http://www.tug.org/mactex/
pdflatex -output-directory=$(dirname $1) $1

# Generate SVG file, use `brew install pdf2svg` to install
pdf2svg ${PDF_FILENAME} ${SVG_FILENAME}
